task: graph_clustering
method: SeeGera
data_root: ~/public_data/pyg_data
supported_datasets:
- Cora
- Citeseer
- Pubmed
- Photo
- Computers
- CS
- Physics
base_config:
  seed: 2024
  device: 0
  epochs: 500
  eval_steps: 50
  mode: last
  l2_normalize: false
  layer: gat
  encoder_activation: prelu
  encoder_channels: 512
  encoder_layers: 2
  encoder_dropout: 0.2
  encoder_norm: none
  num_heads: 4
  decoder_channels: 32
  decoder_layers: 1
  decoder_dropout: 0.2
  decoder_norm: none
  feature_mask_rate: 0.7
  edge_mask_rate: 0.3
  latent_kl_weight: 0.0001
  recon_losses:
  - bce
  - mse
  - sce
  lr: 0.0001
  weight_decay: 5.0e-05
