task: heterogeneous_node_classification
method: HGT
data_root: ~/public_data/pyg_data
supported_datasets:
- DBLP
- ACM
- IMDB
base_config:
  seed: 2024
  device: 0
  epochs: 500
  eval_steps: 50
  nodeclas_lr: 0.01
  nodeclas_weight_decay: 5.0e-05
  mode: cat
  l2_normalize: false
  layer: hgt
  encoder_channels: 256
  encoder_layers: 2
  num_heads: 4
  encoder_dropout: 0.2
  lr: 0.003
  weight_decay: 5.0e-05
  encoder_activation: gelu
