task: graph_classification
method: S3GCL
data_root: ~/public_data/pyg_data
supported_datasets:
- IMDB-BINARY
- IMDB-MULTI
- PROTEINS
- COLLAB
- MUTAG
- REDDIT-BINARY
- NCI1
base_config:
  seed: 2024
  device: 0
  epochs: 200
  eval_steps: 5
  graphclas_lr: 0.01
  graphclas_weight_decay: 5.0e-05
  mode: last
  l2_normalize: false
  pooling: sum
  layer: gin
  encoder_layers: 2
  encoder_channels: 256
  encoder_dropout: 0.5
  encoder_norm: none
  optimizer: adam
  weight_decay: 1.0e-05
  encoder_activation: prelu
  spectral_hops: 2
  spatial_edge_drop_rate: 0.2
  feat_drop_rate: 0.2
  tau: 0.4
  lr: 0.001
